[tool.poetry]
name = "hexlet-code"
version = "0.1.0"
description = "Training Project 2"
authors = ["Kirill Chistov <kirill.v.chistov@yandex.ru>"]
readme = "README.md"
packages = [{include = "gendiff"}, {include = "dsa_lab"}]

[tool.poetry.scripts]
gendiff = "gendiff.scripts.gendiff:main"

[tool.poetry.dependencies]
python = "^3.9"
# argparse = "^1.4.0"
pyyaml = "^6.0.3"
fastapi = "^0.115.0"
uvicorn = {extras = ["standard"], version = "^0.32.0"}
jinja2 = "^3.1.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "flake8 (>=7.3.0,<8.0.0)",
    "pytest (>=8.3,<9.0)",
    "pytest-cov (>=5.0,<6.0)"
]
